version: '2'
services:
  girder:
    image: openchemistry/mongochemserver:latest
    command: -d ${MONGODB_URL} ${GIRDER_EXTRA_ARGS}
    volumes:
     - assetstore:/assetstore
     - keys:/keys
    ports:
      - 127.0.0.1:8080:8080

  rabbitmq:
      image: rabbitmq

  celery_command:
    image: openchemistry/celery_worker:latest
    env_file:
      - ${GIRDER_DOCKER_DIR}/celery/celery.env
    command: celery worker --app=cumulus -b ${RABBITMQ_URL} -n command --config=cumulus.celery.commandconfig --loglevel=INFO
    depends_on:
      - 'rabbitmq'
    volumes:
     - keys:/keys

  celery_monitor:
    image: openchemistry/celery_worker:latest
    env_file:
      - ${GIRDER_DOCKER_DIR}/celery/celery.env
    command: celery worker --app=cumulus -b ${RABBITMQ_URL} -n monitor -Q monitor --config=cumulus.celery.monitorconfig --loglevel=INFO
    depends_on:
      - 'rabbitmq'
    volumes:
     - keys:/keys

volumes:
    assetstore:
    keys:

